fix mplementing WAN failover ( OFW-5250 )
[Issue]
- Untagged (macvlan) virtual interfaces can not be created.
- Tagged VLAN interface has invalid mac

[Solution]
- Impleement Untagged virtual interface creation/deletion.
- Implement retry mechanism to MAC address setting logic since
  sometimes the underlying component/HAL may return ann invalid
  mac at the first trial.

Upstream candidate: Yes

Signed-off-by: Devin Mungan(dmungan@libertyglobal.com)

fix compilation errors error: format not a string literal and no format arguments [-Werror=format-security]
v_secure_system(cmd);

Signed-off-by: BijeeshaVS <bvattakaithayilsudha.contractor@libertyglobal.com>

fix erouter0 discover option 61 IAID must be last 4 octets of MAC address ( OFW-5140 )

BUG DESCRIPTION:
When hex string for MACAddress was constructed from
unsigned long long int "number" using snprintf and format specifier
as "%08llx", leading zeros were not getting added for larger values
of number. Thus macAddress string for erouter0 had incorrect value
(missing leading zeroes). Note that this conversion is done to add
mac offsets for "mg0" and "voip0".

FIX DESCRIPTION:
Updated the minimum width in format specifier to 16 chars so that
resulting string will have leading zeroes added.

TESTING PERFORMED:
Verified that erouter0 MACAddress shown by "ifconfig erouter0"
matches with the MACAddress displayed on the MV3 Hardware and also
matches with value returned by platform_hal_GetBaseMacAddress()