fix mplementing WAN failover ( OFW-5250 )
[Issue]
- Untagged (macvlan) virtual interfaces can not be created.
- Tagged VLAN interface has invalid mac

[Solution]
- Impleement Untagged virtual interface creation/deletion.
- Implement retry mechanism to MAC address setting logic since
  sometimes the underlying component/HAL may return ann invalid
  mac at the first trial.

Upstream candidate: Yes

Signed-off-by: Devin Mungan(dmungan@libertyglobal.com)

fix compilation errors error: format not a string literal and no format arguments [-Werror=format-security]
v_secure_system(cmd);

Signed-off-by: BijeeshaVS <bvattakaithayilsudha.contractor@libertyglobal.com>